[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions.csv
extra_scripts =
    pre:autorev.py
lib_deps =
    zinggjm/GxEPD2
    h2zero/NimBLE-Arduino

[env:panel]
board = adafruit_feather_esp32_v2
build_flags =
	'-D PARTIAL_REFRESH'
#	'-D INVERT_PULSE_CLEANUP'
	'-D FULL_REFRESH_INTERVAL_MIN=15'
#	'-D GABEN_STARTUP'
    '-D EPD_EN=(14)'
    '-D EPD_BUSY=(32)'
    '-D EPD_RESET=(15)'
    '-D SRAM_CS=(33)'
    '-D EPD_DC=(27)'
    '-D EPD_CS=(13)'
# you can add '-D STARTUP_DELAY_MS=5000'
# or similar to delay initial startup which can be useful for debuggings